toubarefane_site:
    resource: "@ToubarefaneSiteBundle/Resources/config/routing.yml"
    prefix:   /

toubarefane_admin:
    resource: "@ToubarefaneSiteBundle/Resources/config/admin_routing.yml"
    prefix:   /admin  
fos_user_security:
    resource: "@ToubarefaneSiteBundle/Resources/routing/security.xml"
fos_user_profile:
    resource: "@ToubarefaneSiteBundle/Resources/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@ToubarefaneSiteBundle/Resources/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@ToubarefaneSiteBundle/Resources/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@ToubarefaneSiteBundle/Resources/routing/change_password.xml"
    prefix: /profile