toubarefane_site:
    resource: "@ToubarefaneSiteBundle/Resources/config/routing.yml"
    prefix:   /site

login:
    pattern:   /login
    defaults:  { _controller: ToubarefaneSiteBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout