security:
    providers:
        main:
            id: fos_user.user_provider.username
    encoders:
        Toubarefane\UserBundle\Entity\User: sha512
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /site
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/site, role: ROLE_USER }
        #- { path: ^/admin, role: ROLE_ADMIN }
       
