# src/Toubarefane/SiteBundle/Resources/config/routing.yml
toubarefaneadmin_login:
    path:      /admin/accueil
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:login }
   
toubarefaneadmin_accueil:
    path:      /{page}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:index, page: 1 }
    requirements:
        page:  \d*

toubarefaneadmin_voir:
    path:      /article/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:voir }
    requirements:
        id:  \d+
toubarefaneadmin_voirtous:
    pattern:      /articles
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:voirtous }
toubarefaneadmin_ajouterother:
    path:      /ajouterother
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:ajouterother }
toubarefaneadmin_ajouteryoutube:
    path:      /ajouteryoutube
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:ajouteryoutube }

toubarefaneadmin_modifier:
    path:      /modifier/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:modifierother }
    requirements:
        id:  \d+
toubarefaneadmin_modifieryoutube:
    path:      /modifieryou/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:modifieryoutube }
    requirements:
        id:  \d+
toubarefaneadmin_supprimer:
    path:      /supprimer/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:supprimer }
    requirements:
        id:  \d+
toubarefaneadmin_sendMail:
    path:      /sendMail/{pseudo}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:sendMail }
    requirements:
        id:  \d+    
toubarefaneadmin_contact:
    path:      /contact
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:contact }
toubarefaneadmin_ajouterreview:
    path:      /ajouter_review
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:create }
   #route des photos     
toubarefaneadmin_ajouterphoto:
    path:      /ajouter_photo
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:ajouterphoto }
toubarefaneadmin_voirphoto:
    path:      /voir_photo/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:voirphoto }
    requirements:
        id:  \d+
toubarefaneadmin_tousphoto:
    path:      /tous_photo
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:tousphoto }
toubarefaneadmin_supprimerphoto:
    path:      /supprimer_photo/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:supprimerphoto }
    requirements:
        id:  \d+

        
    #route des audios
toubarefaneadmin_ajouteraudio:
    path:      /ajouter_audio
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:ajouteraudio }
toubarefaneadmin_tousaudio:
    path:      /tous_audio
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:tousaudio }
toubarefaneadmin_supprimeraudio:
    path:      /supprimer_audio/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:supprimeraudio }
    requirements:
        id:  \d+
toubarefaneadmin_modifieraudio:
    path:      /modifier_audio/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:modifieraudio }
    requirements:
        id:  \d+

    #route des videos
toubarefaneadmin_ajoutervideo:
    path:      /ajouter_video
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:ajoutervideo }
toubarefaneadmin_tousvideo:
    path:      /tous_video
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:voirtousvideo }
toubarefaneadmin_supprimervideo:
    path:      /supprimer_video/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:supprimervideo }
    requirements:
        id:  \d+
toubarefaneadmin_modifiervideo:
    path:      /modifier_video/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:modifiervideo }
    requirements:
        id:  \d+
        
        #graphe   gaz 03046                    edf 50153
 
toubarefaneadmin_flot:
    path:      /flot
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:flot }
toubarefaneadmin_morris:
    path:      /morris
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:morris }
toubarefaneadmin_table:
    path:      /table
    defaults:  { _controller: ToubarefaneSiteBundle:Admin:table }
