# src/Toubarefane/SiteBundle/Resources/config/routing.yml

toubarefanesite_accueil:
    path:      /{page}
    defaults:  { _controller: ToubarefaneSiteBundle:Site:index, page: 1 }
    requirements:
        page:  \d*

toubarefanesite_voir:
    path:      /article/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Site:voir }
    requirements:
        id:  \d+
toubarefanesite_album:
    path:      /album
    defaults:  { _controller: ToubarefaneSiteBundle:Site:album }
toubarefanesite_voirtous:
    path:      /articles
    defaults:  { _controller: ToubarefaneSiteBundle:Site:voirtous }
toubarefanesite_ajouter:
    path:      /ajouter
    defaults:  { _controller: ToubarefaneSiteBundle:Site:ajouter }

toubarefanesite_modifier:
    path:      /modifier/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Site:modifier }
    requirements:
        id:  \d+

toubarefanesite_supprimer:
    path:      /supprimer/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Site:supprimer }
    requirements:
        id:  \d+
toubarefanesite_sendMail:
    path:      /sendMail/{pseudo}
    defaults:  { _controller: ToubarefaneSiteBundle:Site:sendMail }
    requirements:
        id:  \d+    
toubarefanesite_contact:
    path:      /contact
    defaults:  { _controller: ToubarefaneSiteBundle:Site:contact }
toubarefanephoto_ajouter:
    path:      /ajouter_photo
    defaults:  { _controller: ToubarefaneSiteBundle:Photo:ajouter }

toubarefanephoto_voir:
    path:      /voir_photo/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Photo:voir }
    requirements:
        id:  \d+
toubarefanephoto_tous:
    path:      /photo/tous
    defaults:  { _controller: ToubarefaneSiteBundle:Photo:voirtous }
toubarefanephoto_supprimer:
    path:      /supprimer_photo/{id}
    defaults:  { _controller: ToubarefaneSiteBundle:Site:supprimer }
    requirements:
        id:  \d+
toubarefaneaudio_tous:
    path:      /audios
    defaults:  { _controller: ToubarefaneSiteBundle:Audio:voirtous }
toubarefaneaudio_kh:
    path:      /audio/khassidas
    defaults:  { _controller: ToubarefaneSiteBundle:Audio:voirkhassida }
toubarefanevideo_kh:
    path:      /video/khassidas
    defaults:  { _controller: ToubarefaneSiteBundle:Video:voirtous }