parameters:
#    toubarefane_site.example.class: Toubarefane\SiteBundle\Example

services:
#    toubarefane_site.example:
#        class: %toubarefane_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
