parameters:
#    toubarefane_site.example.class: Toubarefane\SiteBundle\Example
services:
    toubarefane_site.fileuploader:
        class: Toubarefane\SiteBundle\Services\FileUploader
        arguments: [ @doctrine.orm.entity_manager, @request_stack, @validator, @kernel ]

services:
    toubarefane_site.antispam:
        class: Toubarefane\SiteBundle\Antispam\ToubarefaneAntispam
        arguments: [@mailer, %locale%, 3]